In [217]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from sklearn.model_selection import train_test_split
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [192]:
data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [182]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [183]:
seed = 7
np.random.seed(seed)

In [184]:
Y = data['Survived']

In [185]:
Y = np.array(Y)

In [194]:
data.loc[data['Sex'] == 'male', 'Sex'] = 1
test_data.loc[test_data['Sex'] == 'male', 'Sex'] = 1

In [195]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [196]:
data.loc[data['Sex'] == 'female', 'Sex'] = 0
test_data.loc[test_data['Sex'] == 'female', 'Sex'] = 0

In [197]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,S

In [199]:
train_data = data.loc[:,['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
test_d = test_data.loc[:,['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]

In [191]:
train_data.head()

   Pclass  Sex   Age  SibSp  Parch
0       3    1  22.0      1      0
1       1    0  38.0      1      0
2       3    0  26.0      0      0
3       1    0  35.0      1      0
4       3    1  35.0      0      0

In [200]:
test_d.head()

   Pclass  Sex   Age  SibSp  Parch
0       3    1  34.5      0      0
1       3    0  47.0      1      0
2       2    1  62.0      0      0
3       3    1  27.0      0      0
4       3    0  22.0      1      1

In [201]:
X = np.nan_to_num(train_data)
X2 = np.nan_to_num(test_d)

In [204]:
X2[0]

array([ 3. ,  1. , 34.5,  0. ,  0. ])

In [206]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=seed)

In [210]:
model = Sequential()
model.add(Dense(8, input_dim=5, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [211]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [212]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=150, batch_size=10)

Train on 596 samples, validate on 295 samples
Epoch 1/150
596/596 [==============================] - 1s 1ms/step - loss: 1.5973 - acc: 0.4128 - val_loss: 0.8427 - val_acc: 0.5288
Epoch 2/150
596/596 [==============================] - 0s 204us/step - loss: 0.6672 - acc: 0.6124 - val_loss: 0.6692 - val_acc: 0.6000
Epoch 3/150
596/596 [==============================] - 0s 195us/step - loss: 0.6321 - acc: 0.6326 - val_loss: 0.6461 - val_acc: 0.6339
Epoch 4/150
596/596 [==============================] - 0s 199us/step - loss: 0.6300 - acc: 0.6510 - val_loss: 0.6392 - val_acc: 0.6441
Epoch 5/150
596/596 [==============================] - 0s 250us/step - loss: 0.6204 - acc: 0.6493 - val_loss: 0.6325 - val_acc: 0.6373
Epoch 6/150
596/596 [==============================] - 0s 267us/step - loss: 0.6133 - acc: 0.6493 - val_loss: 0.6262 - val_acc: 0.6441
Epoch 7/150
596/596 [==============================] - 0s 255us/step - loss: 0.6062 - acc: 0.6644 - val_loss: 0.6256 - val_acc: 0.6339
Epoch 8/150
596/596 [==============================] - 0s 220us/step - loss: 0.5974 - acc: 0.6779 - val_loss: 0.6167 - val_acc: 0.6407
Epoch 9/150
596/596 [==============================] - 0s 226us/step - loss: 0.5901 - acc: 0.6644 - val_loss: 0.6106 - val_acc: 0.6475
Epoch 10/150
596/596 [==============================] - 0s 210us/step - loss: 0.5811 - acc: 0.6930 - val_loss: 0.5962 - val_acc: 0.7017
Epoch 11/150
596/596 [==============================] - 0s 223us/step - loss: 0.5710 - acc: 0.7030 - val_loss: 0.6010 - val_acc: 0.6441
Epoch 12/150
596/596 [==============================] - 0s 289us/step - loss: 0.5598 - acc: 0.7198 - val_loss: 0.5910 - val_acc: 0.6780
Epoch 13/150
596/596 [==============================] - 0s 255us/step - loss: 0.5548 - acc: 0.7148 - val_loss: 0.5771 - val_acc: 0.7085
Epoch 14/150
596/596 [==============================] - 0s 234us/step - loss: 0.5469 - acc: 0.7215 - val_loss: 0.5677 - val_acc: 0.7288
Epoch 15/150
596/596 [==============================] - 0s 200us/step - loss: 0.5371 - acc: 0.7450 - val_loss: 0.5715 - val_acc: 0.7186
Epoch 16/150
596/596 [==============================] - 0s 258us/step - loss: 0.5308 - acc: 0.7517 - val_loss: 0.5546 - val_acc: 0.7390
Epoch 17/150
596/596 [==============================] - 0s 253us/step - loss: 0.5223 - acc: 0.7601 - val_loss: 0.5497 - val_acc: 0.7695
Epoch 18/150
596/596 [==============================] - 0s 246us/step - loss: 0.5207 - acc: 0.7567 - val_loss: 0.5521 - val_acc: 0.7661
Epoch 19/150
596/596 [==============================] - 0s 223us/step - loss: 0.5105 - acc: 0.7802 - val_loss: 0.5478 - val_acc: 0.7729
Epoch 20/150
596/596 [==============================] - 0s 282us/step - loss: 0.5061 - acc: 0.7768 - val_loss: 0.5386 - val_acc: 0.7763
Epoch 21/150
596/596 [==============================] - 0s 273us/step - loss: 0.5020 - acc: 0.7802 - val_loss: 0.5415 - val_acc: 0.7627
Epoch 22/150
596/596 [==============================] - 0s 197us/step - loss: 0.4993 - acc: 0.7919 - val_loss: 0.5345 - val_acc: 0.7424
Epoch 23/150
596/596 [==============================] - 0s 200us/step - loss: 0.4953 - acc: 0.7852 - val_loss: 0.5316 - val_acc: 0.7627
Epoch 24/150
596/596 [==============================] - 0s 298us/step - loss: 0.4882 - acc: 0.7936 - val_loss: 0.5275 - val_acc: 0.7593
Epoch 25/150
596/596 [==============================] - 0s 229us/step - loss: 0.4852 - acc: 0.8054 - val_loss: 0.5274 - val_acc: 0.7695
Epoch 26/150
596/596 [==============================] - 0s 199us/step - loss: 0.4808 - acc: 0.8104 - val_loss: 0.5293 - val_acc: 0.7695
Epoch 27/150
596/596 [==============================] - 0s 260us/step - loss: 0.4746 - acc: 0.8121 - val_loss: 0.5258 - val_acc: 0.7627
Epoch 28/150
596/596 [==============================] - 0s 288us/step - loss: 0.4766 - acc: 0.8087 - val_loss: 0.5218 - val_acc: 0.7661
Epoch 29/150
596/596 [==============================] - 0s 244us/step - loss: 0.4730 - acc: 0.8104 - val_loss: 0.5215 - val_acc: 0.7661
Epoch 30/150
596/596 [==============================] - 0s 228us/step - loss: 0.4691 - acc: 0.8121 - val_loss: 0.5309 - val_acc: 0.7729
Epoch 31/150
596/596 [==============================] - 0s 267us/step - loss: 0.4650 - acc: 0.8104 - val_loss: 0.5270 - val_acc: 0.7729
Epoch 32/150
596/596 [==============================] - 0s 219us/step - loss: 0.4652 - acc: 0.8121 - val_loss: 0.5533 - val_acc: 0.7797
Epoch 33/150
596/596 [==============================] - 0s 222us/step - loss: 0.4634 - acc: 0.8104 - val_loss: 0.5200 - val_acc: 0.7763
Epoch 34/150
596/596 [==============================] - 0s 201us/step - loss: 0.4600 - acc: 0.8104 - val_loss: 0.5155 - val_acc: 0.7763
Epoch 35/150
596/596 [==============================] - 0s 229us/step - loss: 0.4566 - acc: 0.8087 - val_loss: 0.5213 - val_acc: 0.7763
Epoch 36/150
596/596 [==============================] - 0s 282us/step - loss: 0.4539 - acc: 0.8104 - val_loss: 0.5105 - val_acc: 0.7559
Epoch 37/150
596/596 [==============================] - 0s 220us/step - loss: 0.4578 - acc: 0.8104 - val_loss: 0.5246 - val_acc: 0.7593
Epoch 38/150
596/596 [==============================] - 0s 204us/step - loss: 0.4502 - acc: 0.8087 - val_loss: 0.5258 - val_acc: 0.7593
Epoch 39/150
596/596 [==============================] - 0s 196us/step - loss: 0.4520 - acc: 0.8087 - val_loss: 0.5104 - val_acc: 0.7559
Epoch 40/150
596/596 [==============================] - 0s 226us/step - loss: 0.4511 - acc: 0.8087 - val_loss: 0.5250 - val_acc: 0.7593
Epoch 41/150
596/596 [==============================] - 0s 251us/step - loss: 0.4486 - acc: 0.8121 - val_loss: 0.5165 - val_acc: 0.7559
Epoch 42/150
596/596 [==============================] - 0s 237us/step - loss: 0.4484 - acc: 0.8138 - val_loss: 0.5194 - val_acc: 0.7593
Epoch 43/150
596/596 [==============================] - 0s 234us/step - loss: 0.4397 - acc: 0.8087 - val_loss: 0.5181 - val_acc: 0.7593
Epoch 44/150
596/596 [==============================] - 0s 244us/step - loss: 0.4396 - acc: 0.8104 - val_loss: 0.5160 - val_acc: 0.7593
Epoch 45/150
596/596 [==============================] - 0s 245us/step - loss: 0.4400 - acc: 0.8171 - val_loss: 0.5534 - val_acc: 0.7729
Epoch 46/150
596/596 [==============================] - 0s 226us/step - loss: 0.4396 - acc: 0.8104 - val_loss: 0.5156 - val_acc: 0.7559
Epoch 47/150
596/596 [==============================] - 0s 195us/step - loss: 0.4337 - acc: 0.8121 - val_loss: 0.5046 - val_acc: 0.7559
Epoch 48/150
596/596 [==============================] - 0s 228us/step - loss: 0.4331 - acc: 0.8087 - val_loss: 0.5035 - val_acc: 0.7559
Epoch 49/150
596/596 [==============================] - 0s 286us/step - loss: 0.4336 - acc: 0.8138 - val_loss: 0.5090 - val_acc: 0.7593
Epoch 50/150
596/596 [==============================] - 0s 207us/step - loss: 0.4288 - acc: 0.8104 - val_loss: 0.5104 - val_acc: 0.7593
Epoch 51/150
596/596 [==============================] - 0s 239us/step - loss: 0.4288 - acc: 0.8138 - val_loss: 0.5208 - val_acc: 0.7593
Epoch 52/150
596/596 [==============================] - 0s 263us/step - loss: 0.4413 - acc: 0.8188 - val_loss: 0.5023 - val_acc: 0.7593
Epoch 53/150
596/596 [==============================] - 0s 208us/step - loss: 0.4288 - acc: 0.8138 - val_loss: 0.5120 - val_acc: 0.7593
Epoch 54/150
596/596 [==============================] - 0s 229us/step - loss: 0.4259 - acc: 0.8154 - val_loss: 0.5135 - val_acc: 0.7593
Epoch 55/150
596/596 [==============================] - 0s 262us/step - loss: 0.4233 - acc: 0.8154 - val_loss: 0.4984 - val_acc: 0.7593
Epoch 56/150
596/596 [==============================] - 0s 229us/step - loss: 0.4241 - acc: 0.8171 - val_loss: 0.5283 - val_acc: 0.7661
Epoch 57/150
596/596 [==============================] - 0s 227us/step - loss: 0.4241 - acc: 0.8138 - val_loss: 0.5191 - val_acc: 0.7627
Epoch 58/150
596/596 [==============================] - 0s 234us/step - loss: 0.4210 - acc: 0.8188 - val_loss: 0.5115 - val_acc: 0.7627
Epoch 59/150
596/596 [==============================] - 0s 250us/step - loss: 0.4210 - acc: 0.8221 - val_loss: 0.5046 - val_acc: 0.7627
Epoch 60/150
596/596 [==============================] - 0s 231us/step - loss: 0.4190 - acc: 0.8171 - val_loss: 0.5129 - val_acc: 0.7627

Epoch 61/150
596/596 [==============================] - 0s 221us/step - loss: 0.4154 - acc: 0.8154 - val_loss: 0.4967 - val_acc: 0.7593
Epoch 62/150
596/596 [==============================] - 0s 247us/step - loss: 0.4161 - acc: 0.8154 - val_loss: 0.4945 - val_acc: 0.7593
Epoch 63/150
596/596 [==============================] - 0s 206us/step - loss: 0.4214 - acc: 0.8121 - val_loss: 0.4945 - val_acc: 0.7593
Epoch 64/150
596/596 [==============================] - 0s 265us/step - loss: 0.4184 - acc: 0.8205 - val_loss: 0.5150 - val_acc: 0.7627
Epoch 65/150
596/596 [==============================] - 0s 249us/step - loss: 0.4193 - acc: 0.8238 - val_loss: 0.4942 - val_acc: 0.7593
Epoch 66/150
596/596 [==============================] - 0s 219us/step - loss: 0.4124 - acc: 0.8188 - val_loss: 0.5025 - val_acc: 0.7627
Epoch 67/150
596/596 [==============================] - 0s 223us/step - loss: 0.4137 - acc: 0.8188 - val_loss: 0.5239 - val_acc: 0.7763
Epoch 68/150
596/596 [==============================] - 0s 259us/step - loss: 0.4107 - acc: 0.8221 - val_loss: 0.5200 - val_acc: 0.7763
Epoch 69/150
596/596 [==============================] - 0s 256us/step - loss: 0.4190 - acc: 0.8087 - val_loss: 0.5147 - val_acc: 0.7661
Epoch 70/150
596/596 [==============================] - 0s 231us/step - loss: 0.4067 - acc: 0.8238 - val_loss: 0.4919 - val_acc: 0.7593
Epoch 71/150
596/596 [==============================] - 0s 229us/step - loss: 0.4141 - acc: 0.8255 - val_loss: 0.5129 - val_acc: 0.7661
Epoch 72/150
596/596 [==============================] - 0s 218us/step - loss: 0.4092 - acc: 0.8221 - val_loss: 0.4990 - val_acc: 0.7627
Epoch 73/150
596/596 [==============================] - 0s 263us/step - loss: 0.4106 - acc: 0.8255 - val_loss: 0.5215 - val_acc: 0.7797
Epoch 74/150
596/596 [==============================] - 0s 251us/step - loss: 0.4121 - acc: 0.8171 - val_loss: 0.4923 - val_acc: 0.7593
Epoch 75/150
596/596 [==============================] - 0s 230us/step - loss: 0.4095 - acc: 0.8255 - val_loss: 0.4965 - val_acc: 0.7593
Epoch 76/150
596/596 [==============================] - 0s 243us/step - loss: 0.4075 - acc: 0.8255 - val_loss: 0.5052 - val_acc: 0.7661
Epoch 77/150
596/596 [==============================] - 0s 272us/step - loss: 0.4053 - acc: 0.8289 - val_loss: 0.4918 - val_acc: 0.7593
Epoch 78/150
596/596 [==============================] - 0s 252us/step - loss: 0.4116 - acc: 0.8322 - val_loss: 0.4908 - val_acc: 0.7593
Epoch 79/150
596/596 [==============================] - 0s 199us/step - loss: 0.4080 - acc: 0.8238 - val_loss: 0.4906 - val_acc: 0.7593
Epoch 80/150
596/596 [==============================] - 0s 229us/step - loss: 0.4021 - acc: 0.8255 - val_loss: 0.5118 - val_acc: 0.7763
Epoch 81/150
596/596 [==============================] - 0s 258us/step - loss: 0.4030 - acc: 0.8289 - val_loss: 0.5125 - val_acc: 0.7797
Epoch 82/150
596/596 [==============================] - 0s 244us/step - loss: 0.4023 - acc: 0.8372 - val_loss: 0.4973 - val_acc: 0.7627
Epoch 83/150
596/596 [==============================] - 0s 229us/step - loss: 0.4027 - acc: 0.8289 - val_loss: 0.5063 - val_acc: 0.7695
Epoch 84/150
596/596 [==============================] - 0s 261us/step - loss: 0.4048 - acc: 0.8272 - val_loss: 0.5086 - val_acc: 0.7695
Epoch 85/150
596/596 [==============================] - 0s 251us/step - loss: 0.3977 - acc: 0.8322 - val_loss: 0.4909 - val_acc: 0.7593
Epoch 86/150
596/596 [==============================] - 0s 232us/step - loss: 0.3991 - acc: 0.8389 - val_loss: 0.5021 - val_acc: 0.7661
Epoch 87/150
596/596 [==============================] - 0s 223us/step - loss: 0.4032 - acc: 0.8272 - val_loss: 0.4984 - val_acc: 0.7627
Epoch 88/150
596/596 [==============================] - 0s 229us/step - loss: 0.3984 - acc: 0.8356 - val_loss: 0.4957 - val_acc: 0.7627
Epoch 89/150
596/596 [==============================] - 0s 272us/step - loss: 0.4015 - acc: 0.8322 - val_loss: 0.5228 - val_acc: 0.7797
Epoch 90/150
596/596 [==============================] - 0s 257us/step - loss: 0.3956 - acc: 0.8406 - val_loss: 0.4898 - val_acc: 0.7593
Epoch 91/150
596/596 [==============================] - 0s 254us/step - loss: 0.3995 - acc: 0.8322 - val_loss: 0.5206 - val_acc: 0.7797
Epoch 92/150
596/596 [==============================] - 0s 256us/step - loss: 0.4018 - acc: 0.8238 - val_loss: 0.4913 - val_acc: 0.7559
Epoch 93/150
596/596 [==============================] - 0s 229us/step - loss: 0.3994 - acc: 0.8305 - val_loss: 0.4978 - val_acc: 0.7661
Epoch 94/150
596/596 [==============================] - 0s 198us/step - loss: 0.3968 - acc: 0.8356 - val_loss: 0.5087 - val_acc: 0.7797
Epoch 95/150
596/596 [==============================] - 0s 196us/step - loss: 0.3958 - acc: 0.8356 - val_loss: 0.5203 - val_acc: 0.7797
Epoch 96/150
596/596 [==============================] - 0s 196us/step - loss: 0.4065 - acc: 0.8389 - val_loss: 0.5142 - val_acc: 0.7797
Epoch 97/150
596/596 [==============================] - 0s 199us/step - loss: 0.3999 - acc: 0.8406 - val_loss: 0.4915 - val_acc: 0.7661
Epoch 98/150
596/596 [==============================] - 0s 260us/step - loss: 0.4000 - acc: 0.8322 - val_loss: 0.4896 - val_acc: 0.7695
Epoch 99/150
596/596 [==============================] - 0s 279us/step - loss: 0.3971 - acc: 0.8339 - val_loss: 0.4928 - val_acc: 0.7661
Epoch 100/150
596/596 [==============================] - 0s 203us/step - loss: 0.3963 - acc: 0.8389 - val_loss: 0.5150 - val_acc: 0.7797
Epoch 101/150
596/596 [==============================] - 0s 207us/step - loss: 0.3983 - acc: 0.8339 - val_loss: 0.4923 - val_acc: 0.7661
Epoch 102/150
596/596 [==============================] - 0s 213us/step - loss: 0.3972 - acc: 0.8356 - val_loss: 0.4970 - val_acc: 0.7729
Epoch 103/150
596/596 [==============================] - 0s 245us/step - loss: 0.3991 - acc: 0.8389 - val_loss: 0.5019 - val_acc: 0.7797
Epoch 104/150
596/596 [==============================] - 0s 226us/step - loss: 0.3950 - acc: 0.8372 - val_loss: 0.5029 - val_acc: 0.7831
Epoch 105/150
596/596 [==============================] - 0s 245us/step - loss: 0.3937 - acc: 0.8389 - val_loss: 0.5044 - val_acc: 0.7831
Epoch 106/150
596/596 [==============================] - 0s 229us/step - loss: 0.3967 - acc: 0.8406 - val_loss: 0.5039 - val_acc: 0.7831
Epoch 107/150
596/596 [==============================] - 0s 220us/step - loss: 0.3935 - acc: 0.8339 - val_loss: 0.4951 - val_acc: 0.7729
Epoch 108/150
596/596 [==============================] - 0s 208us/step - loss: 0.3955 - acc: 0.8406 - val_loss: 0.4903 - val_acc: 0.7729
Epoch 109/150
596/596 [==============================] - 0s 218us/step - loss: 0.3957 - acc: 0.8322 - val_loss: 0.5042 - val_acc: 0.7831
Epoch 110/150
596/596 [==============================] - 0s 235us/step - loss: 0.4038 - acc: 0.8272 - val_loss: 0.4981 - val_acc: 0.7729
Epoch 111/150
596/596 [==============================] - 0s 217us/step - loss: 0.3980 - acc: 0.8423 - val_loss: 0.4937 - val_acc: 0.7661
Epoch 112/150
596/596 [==============================] - 0s 213us/step - loss: 0.3962 - acc: 0.8372 - val_loss: 0.5008 - val_acc: 0.7729
Epoch 113/150
596/596 [==============================] - 0s 241us/step - loss: 0.3944 - acc: 0.8423 - val_loss: 0.4930 - val_acc: 0.7695
Epoch 114/150
596/596 [==============================] - 0s 247us/step - loss: 0.3974 - acc: 0.8389 - val_loss: 0.4943 - val_acc: 0.7661
Epoch 115/150
596/596 [==============================] - 0s 230us/step - loss: 0.3987 - acc: 0.8339 - val_loss: 0.5143 - val_acc: 0.7831
Epoch 116/150
596/596 [==============================] - 0s 224us/step - loss: 0.3912 - acc: 0.8406 - val_loss: 0.4917 - val_acc: 0.7729
Epoch 117/150
596/596 [==============================] - 0s 208us/step - loss: 0.4002 - acc: 0.8406 - val_loss: 0.5069 - val_acc: 0.7831
Epoch 118/150
596/596 [==============================] - 0s 251us/step - loss: 0.3928 - acc: 0.8372 - val_loss: 0.5007 - val_acc: 0.7831
Epoch 119/150
596/596 [==============================] - 0s 251us/step - loss: 0.3898 - acc: 0.8339 - val_loss: 0.4911 - val_acc: 0.7763
Epoch 120/150
596/596 [==============================] - 0s 260us/step - loss: 0.3973 - acc: 0.8406 - val_loss: 0.5365 - val_acc: 0.7831
Epoch 121/150

596/596 [==============================] - 0s 228us/step - loss: 0.3983 - acc: 0.8339 - val_loss: 0.5054 - val_acc: 0.7831
Epoch 122/150
596/596 [==============================] - 0s 212us/step - loss: 0.3935 - acc: 0.8339 - val_loss: 0.5004 - val_acc: 0.7831
Epoch 123/150
596/596 [==============================] - 0s 205us/step - loss: 0.3990 - acc: 0.8289 - val_loss: 0.5378 - val_acc: 0.7864
Epoch 124/150
596/596 [==============================] - 0s 248us/step - loss: 0.3920 - acc: 0.8389 - val_loss: 0.5302 - val_acc: 0.7797
Epoch 125/150
596/596 [==============================] - 0s 241us/step - loss: 0.3946 - acc: 0.8356 - val_loss: 0.4991 - val_acc: 0.7763
Epoch 126/150
596/596 [==============================] - 0s 227us/step - loss: 0.3923 - acc: 0.8406 - val_loss: 0.5233 - val_acc: 0.7797
Epoch 127/150
596/596 [==============================] - 0s 216us/step - loss: 0.3932 - acc: 0.8389 - val_loss: 0.5020 - val_acc: 0.7831
Epoch 128/150
596/596 [==============================] - 0s 215us/step - loss: 0.3910 - acc: 0.8372 - val_loss: 0.5134 - val_acc: 0.7831
Epoch 129/150
596/596 [==============================] - 0s 219us/step - loss: 0.3913 - acc: 0.8423 - val_loss: 0.4929 - val_acc: 0.7763
Epoch 130/150
596/596 [==============================] - 0s 243us/step - loss: 0.3919 - acc: 0.8406 - val_loss: 0.5034 - val_acc: 0.7831
Epoch 131/150
596/596 [==============================] - 0s 239us/step - loss: 0.3887 - acc: 0.8406 - val_loss: 0.4923 - val_acc: 0.7763
Epoch 132/150
596/596 [==============================] - 0s 231us/step - loss: 0.3895 - acc: 0.8540 - val_loss: 0.4931 - val_acc: 0.7763
Epoch 133/150
596/596 [==============================] - 0s 225us/step - loss: 0.3958 - acc: 0.8389 - val_loss: 0.5080 - val_acc: 0.7831
Epoch 134/150
596/596 [==============================] - 0s 224us/step - loss: 0.3923 - acc: 0.8423 - val_loss: 0.4958 - val_acc: 0.7797
Epoch 135/150
596/596 [==============================] - 0s 244us/step - loss: 0.3992 - acc: 0.8339 - val_loss: 0.5144 - val_acc: 0.7831
Epoch 136/150
596/596 [==============================] - 0s 242us/step - loss: 0.3922 - acc: 0.8440 - val_loss: 0.5004 - val_acc: 0.7763
Epoch 137/150
596/596 [==============================] - 0s 255us/step - loss: 0.3920 - acc: 0.8440 - val_loss: 0.5036 - val_acc: 0.7831
Epoch 138/150
596/596 [==============================] - 0s 221us/step - loss: 0.3891 - acc: 0.8473 - val_loss: 0.5067 - val_acc: 0.7831
Epoch 139/150
596/596 [==============================] - 0s 242us/step - loss: 0.3895 - acc: 0.8456 - val_loss: 0.4944 - val_acc: 0.7797
Epoch 140/150
596/596 [==============================] - 0s 241us/step - loss: 0.3868 - acc: 0.8406 - val_loss: 0.5249 - val_acc: 0.7797
Epoch 141/150
596/596 [==============================] - 0s 213us/step - loss: 0.3931 - acc: 0.8440 - val_loss: 0.4938 - val_acc: 0.7831
Epoch 142/150
596/596 [==============================] - 0s 200us/step - loss: 0.4003 - acc: 0.8322 - val_loss: 0.5091 - val_acc: 0.7831
Epoch 143/150
596/596 [==============================] - 0s 197us/step - loss: 0.3876 - acc: 0.8473 - val_loss: 0.5008 - val_acc: 0.7831
Epoch 144/150
596/596 [==============================] - 0s 217us/step - loss: 0.3883 - acc: 0.8406 - val_loss: 0.4939 - val_acc: 0.7763
Epoch 145/150
596/596 [==============================] - 0s 225us/step - loss: 0.3957 - acc: 0.8406 - val_loss: 0.4997 - val_acc: 0.7831
Epoch 146/150
596/596 [==============================] - 0s 213us/step - loss: 0.3907 - acc: 0.8440 - val_loss: 0.5144 - val_acc: 0.7831
Epoch 147/150
596/596 [==============================] - 0s 223us/step - loss: 0.3886 - acc: 0.8473 - val_loss: 0.5063 - val_acc: 0.7831
Epoch 148/150
596/596 [==============================] - 0s 230us/step - loss: 0.3904 - acc: 0.8372 - val_loss: 0.4961 - val_acc: 0.7831
Epoch 149/150
596/596 [==============================] - 0s 194us/step - loss: 0.3891 - acc: 0.8389 - val_loss: 0.5196 - val_acc: 0.7797
Epoch 150/150
596/596 [==============================] - 0s 199us/step - loss: 0.3888 - acc: 0.8473 - val_loss: 0.4976 - val_acc: 0.7831

In [213]:
model.predict_classes(X2)

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

In [223]:
def create_model(optimizer='rmsprop', init='glorot_uniform'):
# create model
    model = Sequential()
    model.add(Dense(12, input_dim=5, kernel_initializer=init, activation='relu')) 
    model.add(Dense(8, kernel_initializer=init, activation='relu')) 
    model.add(Dense(1, kernel_initializer=init, activation='sigmoid'))
  # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) 
    return model

In [ ]:
model = KerasClassifier(build_fn=create_model, verbose=0)
optimizers = ['rmsprop', 'adam']
inits = ['glorot_uniform', 'normal', 'uniform']
epochs = [50, 100, 150]
batches = [5, 10, 20]
param_grid = dict(optimizer=optimizers, epochs=epochs, batch_size=batches, init=inits) 
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid_result = grid.fit(X, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))