In [95]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from sklearn.model_selection import train_test_split

In [192]:
data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [182]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [183]:
seed = 7
np.random.seed(seed)

In [184]:
Y = data['Survived']

In [185]:
Y = np.array(Y)

In [194]:
data.loc[data['Sex'] == 'male', 'Sex'] = 1
test_data.loc[test_data['Sex'] == 'male', 'Sex'] = 1

In [195]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [196]:
data.loc[data['Sex'] == 'female', 'Sex'] = 0
test_data.loc[test_data['Sex'] == 'female', 'Sex'] = 0

In [190]:
train_data = data.loc[:,['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
test_d = test_data.loc[:,['Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]

In [191]:
train_data.head()

   Pclass  Sex   Age  SibSp  Parch
0       3    1  22.0      1      0
1       1    0  38.0      1      0
2       3    0  26.0      0      0
3       1    0  35.0      1      0
4       3    1  35.0      0      0

test_d.head()

In [139]:
X = np.nan_to_num(train_data)
X2 = np.nan_to_num(test_data)

In [165]:
test_data.head()

   Pclass  Sex   Age  SibSp  Parch
0       3    1  34.5      0      0
1       3    0  47.0      1      0
2       2    1  62.0      0      0
3       3    1  27.0      0      0
4       3    0  22.0      1      1

In [166]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=seed)

In [167]:
model = Sequential()
model.add(Dense(8, input_dim=6, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [168]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [169]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=150, batch_size=10)

Train on 596 samples, validate on 295 samples
Epoch 1/150
596/596 [==============================] - 1s 1ms/step - loss: 0.6611 - acc: 0.6258 - val_loss: 0.6641 - val_acc: 0.5966
Epoch 2/150
596/596 [==============================] - 0s 257us/step - loss: 0.6412 - acc: 0.6258 - val_loss: 0.6552 - val_acc: 0.5966
Epoch 3/150
596/596 [==============================] - 0s 252us/step - loss: 0.6280 - acc: 0.6258 - val_loss: 0.6411 - val_acc: 0.5966
Epoch 4/150
596/596 [==============================] - 0s 221us/step - loss: 0.6034 - acc: 0.6258 - val_loss: 0.6052 - val_acc: 0.5966
Epoch 5/150
596/596 [==============================] - 0s 182us/step - loss: 0.5608 - acc: 0.6258 - val_loss: 0.5610 - val_acc: 0.5966
Epoch 6/150
596/596 [==============================] - 0s 196us/step - loss: 0.5160 - acc: 0.6258 - val_loss: 0.5296 - val_acc: 0.5966
Epoch 7/150
596/596 [==============================] - 0s 249us/step - loss: 0.4254 - acc: 0.6359 - val_loss: 0.4235 - val_acc: 0.7492
Epoch 8/150
596/596 [==============================] - 0s 265us/step - loss: 0.3711 - acc: 0.8205 - val_loss: 0.3838 - val_acc: 0.8508
Epoch 9/150
596/596 [==============================] - 0s 273us/step - loss: 0.3404 - acc: 0.8641 - val_loss: 0.3561 - val_acc: 0.8814
Epoch 10/150
596/596 [==============================] - 0s 247us/step - loss: 0.3127 - acc: 0.9161 - val_loss: 0.3331 - val_acc: 0.8949
Epoch 11/150
596/596 [==============================] - 0s 239us/step - loss: 0.2930 - acc: 0.9379 - val_loss: 0.3127 - val_acc: 0.9051
Epoch 12/150
596/596 [==============================] - 0s 246us/step - loss: 0.2739 - acc: 0.9497 - val_loss: 0.2919 - val_acc: 0.9254
Epoch 13/150
596/596 [==============================] - 0s 261us/step - loss: 0.2558 - acc: 0.9664 - val_loss: 0.2809 - val_acc: 0.9254
Epoch 14/150
596/596 [==============================] - 0s 236us/step - loss: 0.2410 - acc: 0.9698 - val_loss: 0.2588 - val_acc: 0.9458
Epoch 15/150
596/596 [==============================] - 0s 216us/step - loss: 0.2278 - acc: 0.9782 - val_loss: 0.2505 - val_acc: 0.9458
Epoch 16/150
596/596 [==============================] - 0s 213us/step - loss: 0.2180 - acc: 0.9782 - val_loss: 0.2302 - val_acc: 0.9932
Epoch 17/150
596/596 [==============================] - 0s 203us/step - loss: 0.2051 - acc: 0.9883 - val_loss: 0.2207 - val_acc: 0.9797
Epoch 18/150
596/596 [==============================] - 0s 213us/step - loss: 0.1949 - acc: 0.9899 - val_loss: 0.2083 - val_acc: 0.9932
Epoch 19/150
596/596 [==============================] - 0s 222us/step - loss: 0.1866 - acc: 0.9933 - val_loss: 0.1976 - val_acc: 0.9966
Epoch 20/150
596/596 [==============================] - 0s 225us/step - loss: 0.1766 - acc: 1.0000 - val_loss: 0.1883 - val_acc: 0.9966
Epoch 21/150
596/596 [==============================] - 0s 245us/step - loss: 0.1689 - acc: 0.9966 - val_loss: 0.1859 - val_acc: 0.9864
Epoch 22/150
596/596 [==============================] - 0s 245us/step - loss: 0.1595 - acc: 0.9983 - val_loss: 0.1649 - val_acc: 0.9966
Epoch 23/150
596/596 [==============================] - 0s 211us/step - loss: 0.1479 - acc: 1.0000 - val_loss: 0.1557 - val_acc: 1.0000
Epoch 24/150
596/596 [==============================] - 0s 196us/step - loss: 0.1401 - acc: 1.0000 - val_loss: 0.1497 - val_acc: 1.0000
Epoch 25/150
596/596 [==============================] - 0s 191us/step - loss: 0.1344 - acc: 1.0000 - val_loss: 0.1437 - val_acc: 1.0000
Epoch 26/150
596/596 [==============================] - 0s 204us/step - loss: 0.1295 - acc: 1.0000 - val_loss: 0.1389 - val_acc: 1.0000
Epoch 27/150
596/596 [==============================] - 0s 256us/step - loss: 0.1247 - acc: 1.0000 - val_loss: 0.1339 - val_acc: 1.0000
Epoch 28/150
596/596 [==============================] - 0s 233us/step - loss: 0.1197 - acc: 1.0000 - val_loss: 0.1283 - val_acc: 1.0000
Epoch 29/150
596/596 [==============================] - 0s 238us/step - loss: 0.1157 - acc: 1.0000 - val_loss: 0.1253 - val_acc: 1.0000
Epoch 30/150
596/596 [==============================] - 0s 252us/step - loss: 0.1114 - acc: 1.0000 - val_loss: 0.1191 - val_acc: 1.0000
Epoch 31/150
596/596 [==============================] - 0s 216us/step - loss: 0.1070 - acc: 1.0000 - val_loss: 0.1146 - val_acc: 1.0000
Epoch 32/150
596/596 [==============================] - 0s 194us/step - loss: 0.1031 - acc: 1.0000 - val_loss: 0.1103 - val_acc: 1.0000
Epoch 33/150
596/596 [==============================] - 0s 218us/step - loss: 0.0997 - acc: 1.0000 - val_loss: 0.1067 - val_acc: 1.0000
Epoch 34/150
596/596 [==============================] - 0s 220us/step - loss: 0.0959 - acc: 1.0000 - val_loss: 0.1054 - val_acc: 1.0000
Epoch 35/150
596/596 [==============================] - 0s 204us/step - loss: 0.0926 - acc: 1.0000 - val_loss: 0.0998 - val_acc: 1.0000
Epoch 36/150
596/596 [==============================] - 0s 190us/step - loss: 0.0899 - acc: 1.0000 - val_loss: 0.0958 - val_acc: 1.0000
Epoch 37/150
596/596 [==============================] - 0s 186us/step - loss: 0.0864 - acc: 1.0000 - val_loss: 0.0926 - val_acc: 1.0000
Epoch 38/150
596/596 [==============================] - 0s 179us/step - loss: 0.0833 - acc: 1.0000 - val_loss: 0.0899 - val_acc: 1.0000
Epoch 39/150
596/596 [==============================] - 0s 184us/step - loss: 0.0805 - acc: 1.0000 - val_loss: 0.0872 - val_acc: 1.0000
Epoch 40/150
596/596 [==============================] - 0s 184us/step - loss: 0.0788 - acc: 1.0000 - val_loss: 0.0858 - val_acc: 1.0000
Epoch 41/150
596/596 [==============================] - 0s 188us/step - loss: 0.0756 - acc: 1.0000 - val_loss: 0.0810 - val_acc: 1.0000
Epoch 42/150
596/596 [==============================] - 0s 217us/step - loss: 0.0734 - acc: 1.0000 - val_loss: 0.0785 - val_acc: 1.0000
Epoch 43/150
596/596 [==============================] - 0s 229us/step - loss: 0.0703 - acc: 1.0000 - val_loss: 0.0758 - val_acc: 1.0000
Epoch 44/150
596/596 [==============================] - 0s 198us/step - loss: 0.0682 - acc: 1.0000 - val_loss: 0.0735 - val_acc: 1.0000
Epoch 45/150
596/596 [==============================] - 0s 186us/step - loss: 0.0662 - acc: 1.0000 - val_loss: 0.0711 - val_acc: 1.0000
Epoch 46/150
596/596 [==============================] - 0s 188us/step - loss: 0.0641 - acc: 1.0000 - val_loss: 0.0689 - val_acc: 1.0000
Epoch 47/150
596/596 [==============================] - 0s 245us/step - loss: 0.0621 - acc: 1.0000 - val_loss: 0.0668 - val_acc: 1.0000
Epoch 48/150
596/596 [==============================] - 0s 188us/step - loss: 0.0598 - acc: 1.0000 - val_loss: 0.0648 - val_acc: 1.0000
Epoch 49/150
596/596 [==============================] - 0s 182us/step - loss: 0.0581 - acc: 1.0000 - val_loss: 0.0629 - val_acc: 1.0000
Epoch 50/150
596/596 [==============================] - 0s 201us/step - loss: 0.0562 - acc: 1.0000 - val_loss: 0.0608 - val_acc: 1.0000
Epoch 51/150
596/596 [==============================] - 0s 233us/step - loss: 0.0545 - acc: 1.0000 - val_loss: 0.0591 - val_acc: 1.0000
Epoch 52/150
596/596 [==============================] - 0s 213us/step - loss: 0.0530 - acc: 1.0000 - val_loss: 0.0570 - val_acc: 1.0000
Epoch 53/150
596/596 [==============================] - 0s 224us/step - loss: 0.0513 - acc: 1.0000 - val_loss: 0.0552 - val_acc: 1.0000
Epoch 54/150
596/596 [==============================] - 0s 262us/step - loss: 0.0496 - acc: 1.0000 - val_loss: 0.0537 - val_acc: 1.0000
Epoch 55/150
596/596 [==============================] - 0s 241us/step - loss: 0.0481 - acc: 1.0000 - val_loss: 0.0522 - val_acc: 1.0000
Epoch 56/150
596/596 [==============================] - 0s 221us/step - loss: 0.0467 - acc: 1.0000 - val_loss: 0.0509 - val_acc: 1.0000
Epoch 57/150
596/596 [==============================] - 0s 192us/step - loss: 0.0454 - acc: 1.0000 - val_loss: 0.0494 - val_acc: 1.0000
Epoch 58/150
596/596 [==============================] - 0s 247us/step - loss: 0.0441 - acc: 1.0000 - val_loss: 0.0476 - val_acc: 1.0000
Epoch 59/150
596/596 [==============================] - 0s 219us/step - loss: 0.0426 - acc: 1.0000 - val_loss: 0.0465 - val_acc: 1.0000
Epoch 60/150
596/596 [==============================] - 0s 256us/step - loss: 0.0414 - acc: 1.0000 - val_loss: 0.0449 - val_acc: 1.0000

Epoch 61/150
596/596 [==============================] - 0s 222us/step - loss: 0.0402 - acc: 1.0000 - val_loss: 0.0438 - val_acc: 1.0000
Epoch 62/150
596/596 [==============================] - 0s 237us/step - loss: 0.0390 - acc: 1.0000 - val_loss: 0.0425 - val_acc: 1.0000
Epoch 63/150
596/596 [==============================] - 0s 242us/step - loss: 0.0380 - acc: 1.0000 - val_loss: 0.0413 - val_acc: 1.0000
Epoch 64/150
596/596 [==============================] - 0s 221us/step - loss: 0.0368 - acc: 1.0000 - val_loss: 0.0403 - val_acc: 1.0000
Epoch 65/150
596/596 [==============================] - 0s 187us/step - loss: 0.0357 - acc: 1.0000 - val_loss: 0.0393 - val_acc: 1.0000
Epoch 66/150
596/596 [==============================] - 0s 215us/step - loss: 0.0347 - acc: 1.0000 - val_loss: 0.0379 - val_acc: 1.0000
Epoch 67/150
596/596 [==============================] - 0s 250us/step - loss: 0.0338 - acc: 1.0000 - val_loss: 0.0367 - val_acc: 1.0000
Epoch 68/150
596/596 [==============================] - 0s 232us/step - loss: 0.0328 - acc: 1.0000 - val_loss: 0.0358 - val_acc: 1.0000
Epoch 69/150
596/596 [==============================] - 0s 232us/step - loss: 0.0319 - acc: 1.0000 - val_loss: 0.0346 - val_acc: 1.0000
Epoch 70/150
596/596 [==============================] - 0s 217us/step - loss: 0.0310 - acc: 1.0000 - val_loss: 0.0339 - val_acc: 1.0000
Epoch 71/150
596/596 [==============================] - 0s 221us/step - loss: 0.0302 - acc: 1.0000 - val_loss: 0.0327 - val_acc: 1.0000
Epoch 72/150
596/596 [==============================] - 0s 220us/step - loss: 0.0295 - acc: 1.0000 - val_loss: 0.0318 - val_acc: 1.0000
Epoch 73/150
596/596 [==============================] - 0s 215us/step - loss: 0.0286 - acc: 1.0000 - val_loss: 0.0310 - val_acc: 1.0000
Epoch 74/150
596/596 [==============================] - 0s 226us/step - loss: 0.0277 - acc: 1.0000 - val_loss: 0.0301 - val_acc: 1.0000
Epoch 75/150
596/596 [==============================] - 0s 235us/step - loss: 0.0270 - acc: 1.0000 - val_loss: 0.0292 - val_acc: 1.0000
Epoch 76/150
596/596 [==============================] - 0s 238us/step - loss: 0.0263 - acc: 1.0000 - val_loss: 0.0286 - val_acc: 1.0000
Epoch 77/150
596/596 [==============================] - 0s 198us/step - loss: 0.0255 - acc: 1.0000 - val_loss: 0.0276 - val_acc: 1.0000
Epoch 78/150
596/596 [==============================] - 0s 235us/step - loss: 0.0248 - acc: 1.0000 - val_loss: 0.0269 - val_acc: 1.0000
Epoch 79/150
596/596 [==============================] - 0s 230us/step - loss: 0.0241 - acc: 1.0000 - val_loss: 0.0264 - val_acc: 1.0000
Epoch 80/150
596/596 [==============================] - 0s 216us/step - loss: 0.0234 - acc: 1.0000 - val_loss: 0.0257 - val_acc: 1.0000
Epoch 81/150
596/596 [==============================] - 0s 225us/step - loss: 0.0229 - acc: 1.0000 - val_loss: 0.0248 - val_acc: 1.0000
Epoch 82/150
596/596 [==============================] - 0s 226us/step - loss: 0.0223 - acc: 1.0000 - val_loss: 0.0241 - val_acc: 1.0000
Epoch 83/150
596/596 [==============================] - 0s 220us/step - loss: 0.0216 - acc: 1.0000 - val_loss: 0.0236 - val_acc: 1.0000
Epoch 84/150
596/596 [==============================] - 0s 223us/step - loss: 0.0210 - acc: 1.0000 - val_loss: 0.0229 - val_acc: 1.0000
Epoch 85/150
596/596 [==============================] - 0s 239us/step - loss: 0.0205 - acc: 1.0000 - val_loss: 0.0223 - val_acc: 1.0000
Epoch 86/150
596/596 [==============================] - 0s 227us/step - loss: 0.0199 - acc: 1.0000 - val_loss: 0.0223 - val_acc: 1.0000
Epoch 87/150
596/596 [==============================] - 0s 222us/step - loss: 0.0194 - acc: 1.0000 - val_loss: 0.0213 - val_acc: 1.0000
Epoch 88/150
596/596 [==============================] - 0s 239us/step - loss: 0.0189 - acc: 1.0000 - val_loss: 0.0207 - val_acc: 1.0000
Epoch 89/150
596/596 [==============================] - 0s 213us/step - loss: 0.0184 - acc: 1.0000 - val_loss: 0.0201 - val_acc: 1.0000
Epoch 90/150
596/596 [==============================] - 0s 202us/step - loss: 0.0179 - acc: 1.0000 - val_loss: 0.0197 - val_acc: 1.0000
Epoch 91/150
596/596 [==============================] - 0s 236us/step - loss: 0.0175 - acc: 1.0000 - val_loss: 0.0191 - val_acc: 1.0000
Epoch 92/150
596/596 [==============================] - 0s 210us/step - loss: 0.0170 - acc: 1.0000 - val_loss: 0.0189 - val_acc: 1.0000
Epoch 93/150
596/596 [==============================] - 0s 218us/step - loss: 0.0165 - acc: 1.0000 - val_loss: 0.0183 - val_acc: 1.0000
Epoch 94/150
596/596 [==============================] - 0s 208us/step - loss: 0.0161 - acc: 1.0000 - val_loss: 0.0179 - val_acc: 1.0000
Epoch 95/150
596/596 [==============================] - 0s 273us/step - loss: 0.0157 - acc: 1.0000 - val_loss: 0.0172 - val_acc: 1.0000
Epoch 96/150
596/596 [==============================] - 0s 258us/step - loss: 0.0153 - acc: 1.0000 - val_loss: 0.0167 - val_acc: 1.0000
Epoch 97/150
596/596 [==============================] - 0s 221us/step - loss: 0.0149 - acc: 1.0000 - val_loss: 0.0163 - val_acc: 1.0000
Epoch 98/150
596/596 [==============================] - 0s 196us/step - loss: 0.0146 - acc: 1.0000 - val_loss: 0.0158 - val_acc: 1.0000
Epoch 99/150
596/596 [==============================] - 0s 271us/step - loss: 0.0142 - acc: 1.0000 - val_loss: 0.0155 - val_acc: 1.0000
Epoch 100/150
596/596 [==============================] - 0s 227us/step - loss: 0.0138 - acc: 1.0000 - val_loss: 0.0150 - val_acc: 1.0000
Epoch 101/150
596/596 [==============================] - 0s 247us/step - loss: 0.0134 - acc: 1.0000 - val_loss: 0.0146 - val_acc: 1.0000
Epoch 102/150
596/596 [==============================] - 0s 226us/step - loss: 0.0131 - acc: 1.0000 - val_loss: 0.0142 - val_acc: 1.0000
Epoch 103/150
596/596 [==============================] - 0s 218us/step - loss: 0.0127 - acc: 1.0000 - val_loss: 0.0140 - val_acc: 1.0000
Epoch 104/150
596/596 [==============================] - 0s 218us/step - loss: 0.0124 - acc: 1.0000 - val_loss: 0.0137 - val_acc: 1.0000
Epoch 105/150
596/596 [==============================] - 0s 239us/step - loss: 0.0121 - acc: 1.0000 - val_loss: 0.0134 - val_acc: 1.0000
Epoch 106/150
596/596 [==============================] - 0s 221us/step - loss: 0.0118 - acc: 1.0000 - val_loss: 0.0129 - val_acc: 1.0000
Epoch 107/150
596/596 [==============================] - 0s 222us/step - loss: 0.0115 - acc: 1.0000 - val_loss: 0.0126 - val_acc: 1.0000
Epoch 108/150
596/596 [==============================] - 0s 226us/step - loss: 0.0112 - acc: 1.0000 - val_loss: 0.0122 - val_acc: 1.0000
Epoch 109/150
596/596 [==============================] - 0s 247us/step - loss: 0.0109 - acc: 1.0000 - val_loss: 0.0120 - val_acc: 1.0000
Epoch 110/150
596/596 [==============================] - 0s 222us/step - loss: 0.0106 - acc: 1.0000 - val_loss: 0.0119 - val_acc: 1.0000
Epoch 111/150
596/596 [==============================] - 0s 218us/step - loss: 0.0103 - acc: 1.0000 - val_loss: 0.0114 - val_acc: 1.0000
Epoch 112/150
596/596 [==============================] - 0s 218us/step - loss: 0.0101 - acc: 1.0000 - val_loss: 0.0112 - val_acc: 1.0000
Epoch 113/150
596/596 [==============================] - 0s 221us/step - loss: 0.0098 - acc: 1.0000 - val_loss: 0.0111 - val_acc: 1.0000
Epoch 114/150
596/596 [==============================] - 0s 239us/step - loss: 0.0096 - acc: 1.0000 - val_loss: 0.0104 - val_acc: 1.0000
Epoch 115/150
596/596 [==============================] - 0s 227us/step - loss: 0.0093 - acc: 1.0000 - val_loss: 0.0102 - val_acc: 1.0000
Epoch 116/150
596/596 [==============================] - 0s 212us/step - loss: 0.0091 - acc: 1.0000 - val_loss: 0.0100 - val_acc: 1.0000
Epoch 117/150
596/596 [==============================] - 0s 222us/step - loss: 0.0089 - acc: 1.0000 - val_loss: 0.0097 - val_acc: 1.0000
Epoch 118/150
596/596 [==============================] - 0s 218us/step - loss: 0.0087 - acc: 1.0000 - val_loss: 0.0095 - val_acc: 1.0000
Epoch 119/150
596/596 [==============================] - 0s 252us/step - loss: 0.0084 - acc: 1.0000 - val_loss: 0.0093 - val_acc: 1.0000
Epoch 120/150
596/596 [==============================] - 0s 294us/step - loss: 0.0082 - acc: 1.0000 - val_loss: 0.0091 - val_acc: 1.0000
Epoch 121/150

596/596 [==============================] - 0s 236us/step - loss: 0.0080 - acc: 1.0000 - val_loss: 0.0090 - val_acc: 1.0000
Epoch 122/150
596/596 [==============================] - 0s 183us/step - loss: 0.0078 - acc: 1.0000 - val_loss: 0.0088 - val_acc: 1.0000
Epoch 123/150
596/596 [==============================] - 0s 199us/step - loss: 0.0076 - acc: 1.0000 - val_loss: 0.0086 - val_acc: 1.0000
Epoch 124/150
596/596 [==============================] - 0s 228us/step - loss: 0.0074 - acc: 1.0000 - val_loss: 0.0082 - val_acc: 1.0000
Epoch 125/150
596/596 [==============================] - 0s 221us/step - loss: 0.0072 - acc: 1.0000 - val_loss: 0.0082 - val_acc: 1.0000
Epoch 126/150
596/596 [==============================] - 0s 221us/step - loss: 0.0071 - acc: 1.0000 - val_loss: 0.0080 - val_acc: 1.0000
Epoch 127/150
596/596 [==============================] - 0s 219us/step - loss: 0.0069 - acc: 1.0000 - val_loss: 0.0076 - val_acc: 1.0000
Epoch 128/150
596/596 [==============================] - 0s 215us/step - loss: 0.0067 - acc: 1.0000 - val_loss: 0.0075 - val_acc: 1.0000
Epoch 129/150
596/596 [==============================] - 0s 219us/step - loss: 0.0066 - acc: 1.0000 - val_loss: 0.0073 - val_acc: 1.0000
Epoch 130/150
596/596 [==============================] - 0s 223us/step - loss: 0.0064 - acc: 1.0000 - val_loss: 0.0071 - val_acc: 1.0000
Epoch 131/150
596/596 [==============================] - 0s 235us/step - loss: 0.0062 - acc: 1.0000 - val_loss: 0.0069 - val_acc: 1.0000
Epoch 132/150
596/596 [==============================] - 0s 203us/step - loss: 0.0061 - acc: 1.0000 - val_loss: 0.0067 - val_acc: 1.0000
Epoch 133/150
596/596 [==============================] - 0s 237us/step - loss: 0.0059 - acc: 1.0000 - val_loss: 0.0067 - val_acc: 1.0000
Epoch 134/150
596/596 [==============================] - 0s 245us/step - loss: 0.0058 - acc: 1.0000 - val_loss: 0.0064 - val_acc: 1.0000
Epoch 135/150
596/596 [==============================] - 0s 250us/step - loss: 0.0056 - acc: 1.0000 - val_loss: 0.0064 - val_acc: 1.0000
Epoch 136/150
596/596 [==============================] - 0s 230us/step - loss: 0.0055 - acc: 1.0000 - val_loss: 0.0062 - val_acc: 1.0000
Epoch 137/150
596/596 [==============================] - 0s 214us/step - loss: 0.0054 - acc: 1.0000 - val_loss: 0.0061 - val_acc: 1.0000
Epoch 138/150
596/596 [==============================] - 0s 217us/step - loss: 0.0052 - acc: 1.0000 - val_loss: 0.0058 - val_acc: 1.0000
Epoch 139/150
596/596 [==============================] - 0s 226us/step - loss: 0.0051 - acc: 1.0000 - val_loss: 0.0057 - val_acc: 1.0000
Epoch 140/150
596/596 [==============================] - 0s 238us/step - loss: 0.0050 - acc: 1.0000 - val_loss: 0.0055 - val_acc: 1.0000
Epoch 141/150
596/596 [==============================] - 0s 225us/step - loss: 0.0049 - acc: 1.0000 - val_loss: 0.0053 - val_acc: 1.0000
Epoch 142/150
596/596 [==============================] - 0s 197us/step - loss: 0.0047 - acc: 1.0000 - val_loss: 0.0052 - val_acc: 1.0000
Epoch 143/150
596/596 [==============================] - 0s 215us/step - loss: 0.0046 - acc: 1.0000 - val_loss: 0.0052 - val_acc: 1.0000
Epoch 144/150
596/596 [==============================] - 0s 186us/step - loss: 0.0045 - acc: 1.0000 - val_loss: 0.0050 - val_acc: 1.0000
Epoch 145/150
596/596 [==============================] - 0s 192us/step - loss: 0.0044 - acc: 1.0000 - val_loss: 0.0048 - val_acc: 1.0000
Epoch 146/150
596/596 [==============================] - 0s 190us/step - loss: 0.0043 - acc: 1.0000 - val_loss: 0.0048 - val_acc: 1.0000
Epoch 147/150
596/596 [==============================] - 0s 188us/step - loss: 0.0042 - acc: 1.0000 - val_loss: 0.0047 - val_acc: 1.0000
Epoch 148/150
596/596 [==============================] - 0s 199us/step - loss: 0.0041 - acc: 1.0000 - val_loss: 0.0045 - val_acc: 1.0000
Epoch 149/150
596/596 [==============================] - 0s 207us/step - loss: 0.0040 - acc: 1.0000 - val_loss: 0.0044 - val_acc: 1.0000
Epoch 150/150
596/596 [==============================] - 0s 187us/step - loss: 0.0039 - acc: 1.0000 - val_loss: 0.0044 - val_acc: 1.0000

In [175]:
model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1]], dtype=int32)